import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/layout/header";

const sora = localFont({
    src: "../fonts/Sora-VariableFont_wght.ttf",
    variable: "--font-sora",
    weight: "100 800",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${sora.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <Header />
                {children}
                {/* 
                    Personal best: <!-- PB --> WPM

                    WPM: <!-- WPM -->
                    Accuracy: <!-- Accuracy -->
                    Time: <!-- Time -->

                    Difficulty:
                    Easy
                    Medium
                    Hard

                    Mode:
                    Timed (60s)
                    Passage

                    <!-- Passage -->

                    Start Typing Test
                    Or click the text and start typing

                    <!-- Test Complete Start -->

                    Test Complete!
                    Solid run. Keep pushing to beat your high score.

                    WPM: <!-- WPM -->
                    Accuracy: <!-- Accuracy -->
                    Characters: <!-- Correct/Incorrect -->

                    Go Again
                    
                    <!-- Test Complete End -->
                */}
            </body>
            <footer className="attribution">
                Challenge by{" "}
                <a href="https://www.frontendmentor.io?ref=challenge">
                    Frontend Mentor
                </a>
                . Coded by <a href="#">Your Name Here</a>.
            </footer>
        </html>
    );
}
