import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const sora = localFont({
    src: "../fonts/Sora-VariableFont_wght.ttf",
    variable: "--font-sora",
    weight: "100 800",
});

export const metadata: Metadata = {
    title: "Frontend Mentor | Typing Speed Test",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${sora.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col bg-neutral-900 text-neutral-50">
                <Header />
                {children}
                {/* 
                    <!-- Test Complete Start -->

                    Test Complete!
                    Solid run. Keep pushing to beat your high score.

                    WPM: <!-- WPM -->
                    Accuracy: <!-- Accuracy -->
                    Characters: <!-- Correct/Incorrect -->

                    Go Again
                    
                    <!-- Test Complete End -->
                */}
                <Footer />
            </body>
        </html>
    );
}
