import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/layout/header";

const sora = localFont({
    src: "../fonts/Sora-VariableFont_wght.ttf",
    variable: "--font-sora",
    weight: "100 800",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${sora.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <Header />
                {children}
            </body>
        </html>
    );
}
